{{- if not .Values.anthropic.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "claude-code.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "claude-code.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.anthropic.inlineSecret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
